### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by alprszr** [burakyilmaz321/tefas-crawler#14]
selamlar,
farklı zamanlarda denememe rağmen aşağıdaki hatayı alıyorum, yardımcı olabilir misin?

SSLError: HTTPSConnectionPool(host='[www.tefas.gov.tr](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/alper/Desktop/fontakip/www.tefas.gov.tr)', port=443): Max retries exceeded with url: /TarihselVeriler.aspx (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)')))

**Comment by alprszr** [comment]
versiyon güncellemesiyle düzeldi, teşekkürler

**Comment by KaanSimsek** [comment]
@alprszr Hangi versiyona geçince düzeldi? 0.4.0'da hata devam ediyor gibi duruyor.
