### ISSUE TITLE
Adding pension funds to Crawler

### ISSUE THREAD

**Issue by mhmtsoydam** [burakyilmaz321/tefas-crawler#17]
Changing "fontip" as "EMK" in Crawler will result in crawling Individual Pension System funds as well. Can we make it optional in Crawler?

**Comment by burakyilmaz321** [comment]
Yes that makes sense 👍 

Also BYF will get "Exchange Traded Funds" I guess.

I'll send a patch whenever I got time. Or feel free to send a PR, if you want.

**Comment by mhmtsoydam** [comment]
Will you push this update on pip?

**Comment by burakyilmaz321** [comment]
done ✅
